# Generated by Django 5.1.3 on 2025-04-21 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('Indefinido', 'Indefinido'), ('Fijo discontinuo', 'Fijo Discontinuo'), ('Tiempo Parcial 15h', 'Tiempo Parcial 15'), ('Tiempo Parcial 20h', 'Tiempo Parcial 20')], default='Indefinido', max_length=20)),
                ('salario', models.FloatField(null=True)),
                ('horas_semanales', models.PositiveIntegerField(null=True)),
                ('dias_vacaciones', models.PositiveIntegerField(null=True)),
                ('horas_extra', models.PositiveIntegerField(null=True)),
                ('faltas', models.PositiveIntegerField(null=True)),
                ('mes', models.PositiveIntegerField(null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('numero_seguridad_social', models.CharField(max_length=100, null=True)),
                ('puesto', models.CharField(choices=[('Camarero', 'Camarero'), ('Cocinero', 'Cocinero'), ('Administrador', 'Administrador')], default='Camarero', max_length=100)),
                ('cuenta_bancaria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Curso', 'En Curso')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_Producto', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.CharField(choices=[('Comida', 'Comida'), ('Bebida', 'Bebida')], default='Comida', max_length=100)),
                ('tipo_categoria', models.CharField(choices=[('Entrantes', 'Entrantes'), ('Platos', 'Platos'), ('Revueltos', 'Revueltos'), ('Verduras', 'Verduras')], default='Platos', max_length=100, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('subcategoria', models.CharField(choices=[('Carne', 'Carne'), ('Pescado', 'Pescado'), ('Arroz', 'Arroz')], default='', max_length=100, null=True)),
                ('stock', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField(null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otros')], default='O', max_length=100)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('id_contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='safadordelasdelicias.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safadordelasdelicias.empleados')),
                ('id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='safadordelasdelicias.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id_linea_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.PositiveIntegerField(default=1)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado'), ('En Retraso', 'En Retraso')], default='Pendiente', max_length=20)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lineas', to='safadordelasdelicias.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='safadordelasdelicias.productos')),
            ],
        ),
    ]
