# Generated by Django 5.1.3 on 2025-04-11 15:40
# Generated by Django 5.1.7 on 2025-04-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safadordelasdelicias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='tipo_contrato',
            field=models.CharField(choices=[('Camarero', 'Camarero'), ('Cocinero', 'Cocinero'), ('Administrador', 'Administrador')], default='Camarero', max_length=20),
        ),
        migrations.AddField(
            model_name='empleados',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='numero_seguridad_social',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='puesto',
            field=models.CharField(choices=[('Camarero', 'Camarero'), ('Cocinero', 'Cocinero'), ('Administrador', 'Administrador')], default='Camarero', max_length=100),
        ),
    ]
